### ISSUE TITLE
Allow to configure event store table name

### ISSUE THREAD

**Issue by lukaszb** [ApplauseOSS/djangoevents#19]
Currently we have hardcoded `event_journal` name for the table (https://github.com/ApplauseOSS/djangoevents/blob/devel/djangoevents/models.py#L19). As not default value might be surprising for library users. Let's use default name (`djangoevents_event`) but allow to configure this.

## Tasks

- [ ] Create `djangoevents.config` module which should read `DJANGOEVENTS_CONFIG` variable from `settings.py`
- [ ] Have a default `djangoevents_event` for table name
- [ ] Use table name from configuration at the model's `Meta`
- [ ] Use table name from configuration at the migration
- [ ] Document this at the readme
- [ ] Updated changelog and let users know of potentially breaking change (they would need to manually rename table or set table name to `event_journal`
